name: CI Workflow

on:
  [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install linters
        run: |
          pip install flake8 mypy

      - name: Run flake8 linter
        run: flake8 run.py roop

      - name: Run mypy static type checker
        run: mypy run.py roop

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CUDA
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Install yt-dlp
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo apt-get install -y python3-tk  # Install Tkinter
          pip3 install yt-dlp

      - name: Download YouTube video
        run: |
          wget -O ".github/examples/youtube.mp4" "https://rr1---sn-gwpa-cive7.googlevideo.com/videoplayback?expire=1728908028&ei=nLYMZ7XOEdHm6dsP29rLsQs&ip=2a02%3A8070%3Ac185%3A5840%3A4c1d%3Aa601%3A5036%3A3ed3&id=o-AC1Ko5gvG6DyzSquFrSo-Ja9z5J3pCAQgb82ym7E7UAb&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1728886428%2C&rms=au%2Cau&bui=AXLXGFSdkbTIOrFZb8G81aoUHxSx1Qs1vHuTwa9hv2RcLcfLZ4JqBY97T-nwCkebMk9l3fWdEcJuiqJy&spc=54MbxbmsrRyQ00WpDom1KoMnzO3nWliIYbq7aO6sdTpwhM_N__noTVC2r1V-&vprv=1&svpuc=1&mime=video%2Fmp4&ns=svT4L0WduAtu_lqLHZbBQQsQ&rqh=1&cnr=14&ratebypass=yes&dur=342.122&lmt=1663957046686395&fexp=24350655,51300761&c=MWEB&sefc=1&txp=5438434&n=ZjJskdmJ7aKMRw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgVZODK22BLGJaxIi2owWM_34ACOiQYfE3mZ3a9b9amcACIAqJKJwYloTs1VdOYT5EWX68oLBx73y0enOfZkHPNxth&title=%E0%A4%A6%E0%A4%BF%E0%A4%B2+%E0%A4%AE%E0%A4%A4+%E0%A4%A4%E0%A5%8B%E0%A5%9C%E0%A5%87+%E0%A4%AE%E0%A4%B0+%E0%A4%9C%E0%A4%BE%E0%A4%8A%E0%A4%97%E0%A5%80+%E0%A4%B0%E0%A4%BE%E0%A4%9C%E0%A4%BE+%E0%A4%A4%E0%A5%87%E0%A4%B0%E0%A5%80+%E0%A4%B8%E0%A5%8B+%7C%7C+%E0%A4%AD%E0%A5%82%E0%A4%AA%E0%A5%87%E0%A4%82%E0%A4%A6%E0%A5%8D%E0%A4%B0+%E0%A4%96%E0%A4%9F%E0%A4%BE%E0%A4%A8%E0%A4%BE+%E0%A4%95%E0%A4%BE+%E0%A4%B8%E0%A4%AC%E0%A4%B8%E0%A5%87+%E0%A4%B9%E0%A4%BF%E0%A4%9F+%E0%A4%B0%E0%A4%B8%E0%A4%BF%E0%A4%AF%E0%A4%BE+%7C%7C+Gurjar+Rasiya+2021&redirect_counter=1&rm=sn-h0jlk76&rrc=104&req_id=99b10e380dc9a3ee&cms_redirect=yes&ipbypass=yes&mh=3J&mip=2409:4043:2114:dd20:213f:5559:1ca8:afc9&mm=31&mn=sn-gwpa-cive7&ms=au&mt=1728886132&mv=m&mvi=1&pl=41&lsparams=ipbypass,met,mh,mip,mm,mn,ms,mv,mvi,pl,rms&lsig=ACJ0pHgwRAIgE3oux82KTHByGyxL5MYRCcvYv_t4YdeQHinRDevONuwCIAoh44Vdtim6uvzFfinC-EMVToK3YEHervV1RpH66P2M"

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Install Python dependencies
        run: pip install -r requirements-headless.txt

      - name: Run Python script
        run: |
          python run.py -s ".github/examples/runningmaneh.png" -t ".github/examples/youtube.mp4" -o ".github/examples/output.mp4" --keep-frames --keep-fps --temp-frame-quality 1 --output-video-quality 1 --execution-provider cpu --execution-threads 1 --frame-processor face_swapper

      # Optional: Uncomment the following to compare videos using PSNR
      # - name: Compare videos using PSNR
      #   run: ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex psnr -f null -

      # Convert output to HD
      - name: Convert output to HD
        run: |
          ffmpeg -i .github/examples/output.mp4 -vf scale=1280:720 -c:v libx264 -preset slow -crf 22 -c:a aac -b:a 128k .github/examples/output_hd.mp4

      # Upload processed original video as artifact
      - name: Upload processed video as artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed-video
          path: .github/examples/output.mp4

      # Upload processed HD video as artifact
      - name: Upload HD processed video as artifact
        uses: actions/upload-artifact@v3
        with:
          name: processed-video-hd
          path: .github/examples/output_hd.mp4
