name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip install flake8
      - run: pip install mypy
      - run: flake8 run.py roop
      - run: mypy run.py roop

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install CUDA
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: pip install -r requirements-headless.txt

      - run: python run.py -s ".github/examples/runningmaneh.png" -t ".github/examples/g.mp4" -o ".github/examples/output.mp4" --keep-frames --keep-fps --temp-frame-quality 1 --output-video-quality 1 --execution-provider cpu --frame-processor face_swapper

     # - run: ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex psnr -f null -

      - name: Convert output to HD
        run: |
          ffmpeg -i .github/examples/output.mp4 -vf "scale=1920:1080" -c:a copy .github/examples/output_hd.mp4

      - name: Upload output_hd.mp4 as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-hd-video
          path: .github/examples/output_hd.mp4
